import React, {useEffect, useState} from "react";
import {ActivityIndicator, FlatList, Pressable, SafeAreaView, StatusBar, StyleSheet, Text, TextInput, View} from "react-native";

const API = process.env.EXPO_PUBLIC_API_URL || "http://10.0.2.2:8000";

export default function App() {
  const [email,setEmail]=useState("client@acme.demo"), [password,setPassword]=useState("Client123!");
  const [session,setSession]=useState(null), [requests,setRequests]=useState([]), [loading,setLoading]=useState(false), [error,setError]=useState("");
  async function signIn(){
    setLoading(true);setError("");
    try{
      const response=await fetch(`${API}/api/auth/login`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({username:email,password}).toString()});
      const data=await response.json();if(!response.ok)throw new Error(data.detail||"Unable to sign in");setSession(data);
    }catch(reason){setError(reason.message)}finally{setLoading(false)}
  }
  useEffect(()=>{if(session)fetch(`${API}/api/travel/requests`,{headers:{Authorization:`Bearer ${session.access_token}`}}).then(r=>r.json()).then(setRequests).catch(()=>setRequests([]))},[session]);
  if(!session)return <SafeAreaView style={s.login}><StatusBar barStyle="light-content"/><View style={s.hero}><Text style={s.mark}>✦</Text><Text style={s.brand}>VoyageAI</Text><Text style={s.title}>Business travel,{`\n`}beautifully managed.</Text><Text style={s.subtitle}>Your journeys, approvals and bookings in one secure mobile workspace.</Text></View><View style={s.form}><Text style={s.label}>WORK EMAIL</Text><TextInput style={s.input} autoCapitalize="none" value={email} onChangeText={setEmail}/><Text style={s.label}>PASSWORD</Text><TextInput style={s.input} secureTextEntry value={password} onChangeText={setPassword}/>{!!error&&<Text style={s.error}>{error}</Text>}<Pressable style={s.button} onPress={signIn}>{loading?<ActivityIndicator color="white"/>:<Text style={s.buttonText}>Sign in →</Text>}</Pressable></View></SafeAreaView>;
  return <SafeAreaView style={s.screen}><StatusBar barStyle="dark-content"/><View style={s.header}><View><Text style={s.eyebrow}>YOUR TRAVEL DESK</Text><Text style={s.heading}>Hello, {session.user.full_name.split(" ")[0]}</Text></View><Pressable onPress={()=>setSession(null)}><Text style={s.logout}>Sign out</Text></Pressable></View><View style={s.tripCard}><Text style={s.cardEyebrow}>TRAVEL, SIMPLIFIED</Text><Text style={s.cardTitle}>Where should business take you next?</Text><Pressable style={s.lightButton}><Text style={s.lightButtonText}>＋ New travel request</Text></Pressable></View><Text style={s.sectionTitle}>Recent requests</Text><FlatList data={requests} keyExtractor={item=>String(item.id)} ListEmptyComponent={<Text style={s.empty}>No requests yet. Your next journey starts here.</Text>} renderItem={({item})=><View style={s.request}><View><Text style={s.reference}>{item.reference}</Text><Text style={s.route}>{item.origin||"—"} → {item.destination}</Text></View><Text style={s.status}>{item.status}</Text></View>}/></SafeAreaView>;
}
const s=StyleSheet.create({login:{flex:1,backgroundColor:"#07182c"},hero:{padding:34,paddingTop:70,flex:1},mark:{color:"#67e3ce",fontSize:36},brand:{color:"white",fontSize:22,fontWeight:"800",marginTop:8},title:{color:"white",fontSize:40,lineHeight:45,fontWeight:"800",marginTop:42},subtitle:{color:"#aebfce",fontSize:15,lineHeight:23,marginTop:16},form:{backgroundColor:"white",padding:28,borderTopLeftRadius:28,borderTopRightRadius:28},label:{fontSize:10,fontWeight:"700",letterSpacing:1.2,color:"#6d7c89",marginTop:12,marginBottom:7},input:{borderWidth:1,borderColor:"#dfe6ec",borderRadius:10,padding:14},button:{backgroundColor:"#725cff",borderRadius:10,padding:16,alignItems:"center",marginTop:22},buttonText:{color:"white",fontWeight:"700"},error:{color:"#b42318",marginTop:10},screen:{flex:1,backgroundColor:"#f4f7fa"},header:{padding:22,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},eyebrow:{fontSize:9,letterSpacing:1.4,color:"#725cff",fontWeight:"700"},heading:{fontSize:25,fontWeight:"800",color:"#13243a",marginTop:5},logout:{color:"#725cff",fontWeight:"600"},tripCard:{margin:18,backgroundColor:"#123b5d",borderRadius:20,padding:25},cardEyebrow:{color:"#67e3ce",fontSize:9,letterSpacing:1.2,fontWeight:"700"},cardTitle:{color:"white",fontSize:25,lineHeight:31,fontWeight:"800",marginVertical:13},lightButton:{backgroundColor:"white",borderRadius:9,padding:13,alignItems:"center",marginTop:8},lightButtonText:{color:"#123b5d",fontWeight:"700"},sectionTitle:{fontSize:18,fontWeight:"800",color:"#13243a",marginHorizontal:20,marginVertical:12},request:{backgroundColor:"white",marginHorizontal:18,marginBottom:10,padding:17,borderRadius:12,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},reference:{fontSize:10,color:"#725cff",fontWeight:"700"},route:{fontSize:14,fontWeight:"700",color:"#13243a",marginTop:4},status:{textTransform:"capitalize",fontSize:10,color:"#6049db",backgroundColor:"#f0edff",padding:7,borderRadius:14},empty:{textAlign:"center",color:"#8997a3",padding:40}});
